data("faithful")
hist(faithful$waiting)
hist(faithful$waiting, probability = TRUE)
hist(faithful$eruptions, probability = TRUE)
plot(faithful)
boxplot(faithful$waiting)
min(faithful$waiting)
max(faithful$waiting)
median(faithful$waiting)
quantile(faithful$waiting)
